version: '3'

services:
    schemaless_json_server:
        image: microservicesforeveryone/data_formats_base
        build: docker/base/
        volumes:
            - ./:/opt
        command: php -S 0.0.0.0:80 -t src/SchemalessJSON/server/

    schemaless_json_client:
        image: microservicesforeveryone/data_formats_base
        volumes:
            - ./:/opt
        command: php src/SchemalessJSON/client.php
        depends_on:
            - schemaless_json_server

    custom_json_serialization_server:
        image: microservicesforeveryone/data_formats_base
        volumes:
            - ./:/opt
        command: php -S 0.0.0.0:80 -t src/CustomJSONSerialization/server/

    custom_json_serialization_client:
        image: microservicesforeveryone/data_formats_base
        volumes:
            - ./:/opt
        command: php src/CustomJSONSerialization/client.php
        depends_on:
            - custom_json_serialization_server

    protocol_buffers_compile:
        image: microservicesforeveryone/communication_styles_base
        volumes:
            - ./:/opt
        command: vendor/bin/protobuf --include-descriptors -i . -o ./src src/ProtocolBuffers/server/meetup.proto

    protocol_buffers_server:
        image: microservicesforeveryone/data_formats_base
        volumes:
            - ./:/opt
        command: php -S 0.0.0.0:80 -t src/ProtocolBuffers/server/
        depends_on:
            - protocol_buffers_compile

    protocol_buffers_client:
        image: microservicesforeveryone/communication_styles_base
        volumes:
            - ./:/opt
        command: php src/ProtocolBuffers/client.php
        depends_on:
            - protocol_buffers_server
            - protocol_buffers_compile

    upcasting_server:
        image: microservicesforeveryone/data_formats_base
        volumes:
            - ./:/opt
        command: php -S 0.0.0.0:80 -t src/Upcasting/server/

    upcasting_client:
        image: microservicesforeveryone/communication_styles_base
        volumes:
            - ./:/opt
        command: php src/Upcasting/client.php
        depends_on:
            - upcasting_server

    json_schema_server:
        image: microservicesforeveryone/data_formats_base
        volumes:
            - ./:/opt
        command: php -S 0.0.0.0:80 -t src/JSONSchema/server/

    json_schema_client:
        image: microservicesforeveryone/communication_styles_base
        volumes:
            - ./:/opt
        command: php src/JSONSchema/client.php
        depends_on:
            - json_schema_server
